optimizer: { type: AdamW, kwargs: { lr: 0.0005, weight_decay: 0.05 } }

scheduler: { type: CosLR, kwargs: { epochs: 300, initial_epochs: 10 } }

dataset:
  {
    train:
      {
        NAME: ModelNet,
        DATA_PATH: data/ModelNet/modelnet40_normal_resampled,
        N_POINTS: 8192,
        NUM_CATEGORY: 40,
        USE_NORMALS: FALSE,
        others: { subset: "train" },
      },
    val:
      {
        _NAME: ModelNet,
        DATA_PATH: data/ModelNet/modelnet40_normal_resampled,
        N_POINTS: 8192,
        NUM_CATEGORY: 40,
        USE_NORMALS: FALSE,
        others: { subset: "test" },
      },
    test:
      {
        NAME: ModelNet,
        DATA_PATH: data/ModelNet/modelnet40_normal_resampled,
        N_POINTS: 8192,
        NUM_CATEGORY: 40,
        USE_NORMALS: FALSE,
        others: { subset: "test" },
      },
  }
model: { NAME: SimSiam, backbone: PointNetfeat, proj_layers: 2 }

npoints: 1024
total_bs: 32
step_per_update: 1
max_epoch: 300
grad_norm_clip: 10

epochs: 100
ckpt_dir: ckpt
