optimizer: { type: AdamW, kwargs: { lr: 0.0005, weight_decay: 0.05 } }

scheduler: { type: CosLR, kwargs: { epochs: 100, initial_epochs: 0 } }

dataset:
  {
    train:
      {
        NAME: ShapeNet,
        DATA_PATH: data/ShapeNet55-34/ShapeNet-55,
        N_POINTS: 8192,
        PC_PATH: data/ShapeNet55-34/shapenet_pc,
        others: { subset: "train", npoints: 1024 },
        augmentation: "holes",
        num_holes: 5,
        augmentation_size: 0.1,
      },
    val:
      {
        NAME: ShapeNet,
        DATA_PATH: data/ShapeNet55-34/ShapeNet-55,
        N_POINTS: 8192,
        PC_PATH: data/ShapeNet55-34/shapenet_pc,
        others: { subset: "test", npoints: 1024 },
      },
    test:
      {
        NAME: ShapeNet,
        DATA_PATH: data/ShapeNet55-34/ShapeNet-55,
        N_POINTS: 8192,
        PC_PATH: data/ShapeNet55-34/shapenet_pc,
        others: { subset: "test", npoints: 1024 },
      },
  }
model: { NAME: SimSiam, backbone: PointNetfeat, proj_layers: 2 }

total_bs: 128
epochs: 100
ckpt_dir: ckpt
