optimizer : {
  name: AdamW,
  kwargs: {
  lr : 0.0005, 
  weight_decay : 0.05
}}

scheduler: {
  type: CosLR,
  kwargs: {
    epochs: 100,
    initial_epochs : 0
}}

dataset : {
  train : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml, 
            others: {subset: 'train', npoints: 1024, batch_size: 32},
            augmentation: 'holes',
            num_holes: 5,
            augmentation_size: 0.1},  
  val : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 1024}},
  test : { _base_: cfgs/dataset_configs/ShapeNet-55.yaml,
            others: {subset: 'test', npoints: 1024}}}
model : {
  NAME: SimSiam,
  backbone: PointNetfeat,
  proj_layers: 2
 }

total_bs : 128
epochs : 100
ckpt_dir: ckpt
